version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - '2000:2000'
    volumes:
      - ./server:/app
      - /app/node_modules
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src